import '../models/car.dart';

class CarService {
  // Mock data - In a real app, this would fetch from an API
  static List<Car> getCars() {
    return [
      Car(
        id: '1',
        name: 'Tesla Model 3',
        brand: 'Tesla',
        model: 'Model 3',
        imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
        pricePerHour: 25.0,
        batteryLevel: 85.0,
        isElectric: true,
        isAvailable: true,
        location: 'Downtown',
        description: 'Premium electric sedan with autopilot features',
        seats: 5,
        transmission: 'Automatic',
        rating: 4.8,
      ),
      Car(
        id: '2',
        name: 'Nissan Leaf',
        brand: 'Nissan',
        model: 'Leaf',
        imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
        pricePerHour: 18.0,
        batteryLevel: 92.0,
        isElectric: true,
        isAvailable: true,
        location: 'Airport',
        description: 'Compact electric car perfect for city driving',
        seats: 5,
        transmission: 'Automatic',
        rating: 4.5,
      ),
      Car(
        id: '3',
        name: 'BMW i3',
        brand: 'BMW',
        model: 'i3',
        imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800',
        pricePerHour: 30.0,
        batteryLevel: 78.0,
        isElectric: true,
        isAvailable: false,
        location: 'Mall',
        description: 'Luxury electric vehicle with premium features',
        seats: 4,
        transmission: 'Automatic',
        rating: 4.7,
      ),
      Car(
        id: '4',
        name: 'Chevrolet Bolt',
        brand: 'Chevrolet',
        model: 'Bolt EV',
        imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
        pricePerHour: 20.0,
        batteryLevel: 65.0,
        isElectric: true,
        isAvailable: true,
        location: 'City Center',
        description: 'Spacious electric hatchback with great range',
        seats: 5,
        transmission: 'Automatic',
        rating: 4.6,
      ),
      Car(
        id: '5',
        name: 'Hyundai Kona Electric',
        brand: 'Hyundai',
        model: 'Kona Electric',
        imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
        pricePerHour: 22.0,
        batteryLevel: 88.0,
        isElectric: true,
        isAvailable: true,
        location: 'Beach',
        description: 'Compact SUV with impressive electric range',
        seats: 5,
        transmission: 'Automatic',
        rating: 4.4,
      ),
      Car(
        id: '6',
        name: 'Audi e-tron',
        brand: 'Audi',
        model: 'e-tron',
        imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
        pricePerHour: 45.0,
        batteryLevel: 95.0,
        isElectric: true,
        isAvailable: true,
        location: 'Downtown',
        description: 'Premium electric SUV with luxury amenities',
        seats: 5,
        transmission: 'Automatic',
        rating: 4.9,
      ),
      Car(
        id: '7',
        name: 'Ford Mustang Mach-E',
        brand: 'Ford',
        model: 'Mustang Mach-E',
        imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
        pricePerHour: 35.0,
        batteryLevel: 70.0,
        isElectric: true,
        isAvailable: true,
        location: 'Stadium',
        description: 'Sporty electric crossover with impressive performance',
        seats: 5,
        transmission: 'Automatic',
        rating: 4.7,
      ),
      Car(
        id: '8',
        name: 'Volkswagen ID.4',
        brand: 'Volkswagen',
        model: 'ID.4',
        imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
        pricePerHour: 28.0,
        batteryLevel: 80.0,
        isElectric: true,
        isAvailable: false,
        location: 'Park',
        description: 'Family-friendly electric SUV',
        seats: 5,
        transmission: 'Automatic',
        rating: 4.5,
      ),
    ];
  }

  static Car? getCarById(String id) {
    try {
      return getCars().firstWhere((car) => car.id == id);
    } catch (e) {
      return null;
    }
  }
}


