// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVENlekT3zlMWJ3BwAfI3F6rMzb9QDkVQ',
    appId: '1:739525730760:web:a750f6c3a31c653c1960fd',
    messagingSenderId: '739525730760',
    projectId: 'carsapp-ff0bd',
    authDomain: 'carsapp-ff0bd.firebaseapp.com',
    storageBucket: 'carsapp-ff0bd.firebasestorage.app',
    measurementId: 'G-65FG5LXZ9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFzcLYKZt-Xs1cki6eAkaM1Ptn56uvQ0g',
    appId: '1:739525730760:android:f7bdcfa825b00f7e1960fd',
    messagingSenderId: '739525730760',
    projectId: 'carsapp-ff0bd',
    storageBucket: 'carsapp-ff0bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoZcttDjt_-vWLi_6l78eYmIdUC1SSH-g',
    appId: '1:739525730760:ios:07bbdfbc011370021960fd',
    messagingSenderId: '739525730760',
    projectId: 'carsapp-ff0bd',
    storageBucket: 'carsapp-ff0bd.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoZcttDjt_-vWLi_6l78eYmIdUC1SSH-g',
    appId: '1:739525730760:ios:07bbdfbc011370021960fd',
    messagingSenderId: '739525730760',
    projectId: 'carsapp-ff0bd',
    storageBucket: 'carsapp-ff0bd.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVENlekT3zlMWJ3BwAfI3F6rMzb9QDkVQ',
    appId: '1:739525730760:web:9a69b1deac32b18f1960fd',
    messagingSenderId: '739525730760',
    projectId: 'carsapp-ff0bd',
    authDomain: 'carsapp-ff0bd.firebaseapp.com',
    storageBucket: 'carsapp-ff0bd.firebasestorage.app',
    measurementId: 'G-31H9JTPCFB',
  );
}
